version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - checkout
      - restore_cache:
        keys:
          - yarn-dependencies-{{ checksum "yarn.lock" }}
          # Fallback to using the latest cache if no exact match is found
          - yarn-dependencies-
      
      - run:
          name: install ruby dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: install node dependencies
          command: |
            yarn install

      - save_cache:
          paths:
            - node_modules
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
