version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - checkout

      dependencies:
        pre:
          - gem install bundler

      # Download and cache dependencies
      - restore_cache:
          keys:
          - bird-finder-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - bird-finder-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: bird-finder-dependencies-{{ checksum "Gemfile.lock" }}
