version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - checkout
      - run:
          name: install ruby dependencies
          command: |
            gem install bundler
            bundle install

          name: install node dependencies
          command: |
            yarn install
