version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      working_directory: ~/bird-finder
      - image: circleci/ruby:2.6-alpine
      environment:
                RAILS_ENV: test
    steps:
      - checkout
      # Restore Cached Dependencies
      - type: cache-resto`re
        name: Restore bundle cache
        key: bird-finder-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: bird-finder-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle`
