version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-dependencies-{{ checksum "yarn.lock" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-yarn-dependencies-

      - restore_cache:
          keys:
            - v1-bundler-dependencies-{{ checksum "Gemfile.lock" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-bundler-dependencies-

      - run:
          name: install ruby dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: install node dependencies
          command: |
            yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-yarn-dependencies-{{ checksum "yarn.lock" }}

      - save_cache:
          paths:
            - vendor/path
          key: v1-bundler-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: run newman
          command: |
            npm install newman@4.5.7
            echo 'export UID=$($COLLECTION_UID)' >> $BASH_ENV
            echo 'export API_KEY=$($POSTMAN_API_KEY)' >> $BASH_ENV
            source $BASH_ENV
            ./node_modules/.bin/newman run "https://api.getpostman.com/collections/$UID?apikey=$API_KEY" \
              --environment "https://api.getpostman.com/environments/UID?apikey=$API_KEY"
