default: &default
  adapter: postgresql
  database: bird_finder 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: bird_finder

test:
  <<: *default
  database: bird_finder_test 

production:
  <<: *default
  database: bird_finder
